version: "3.7"
services:
  app:
    container_name: futbob
    restart: always
    build: .
    ports:
      - "7000:7000"
    env_file: .env
    environment:
      - BASE_API_URL=$BASE_API_URL
      - HASH_SALT=$HASH_SALT
      - SECRET=$SECRET
      - PORT=$PORT
      - MONGO_DB_URI=mongodb://mongo/
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo
    volumes:
      - dbdata:/data/db
    ports:
      - 27017:27017

volumes:
  dbdata: